[build]
  command = "npm i -gs yarn && yarn build"
  publish = "public"
[[redirects]]
from = "/discord"
to = "https://discord.gg/XafZ3ZM"
status = 301
force = true
[[redirects]]
from = "/market"
to = "https://docs.google.com/spreadsheets/d/1U5a7bMPuVRVEDjxOQML_Oq_q1GBsDQXWFBu01kD6zpg"
status = 301
force = true
[[redirects]]
from = "/price-check-guide"
to = "https://docs.google.com/spreadsheets/d/13arzuRizakKuCCyFsuSD9w4F48v8Yj48ZTL_fPrsuTI"
status = 301
force = true
[[redirects]]
from = "/bossing"
to = "https://docs.google.com/spreadsheets/d/1o0jZaUZ1QbYLfZgieKGPqwG05KkZjSAVGsn7jeKBORw/edit?usp=sharing"
status = 301
force = true
[[redirects]]
from = "/monster-cards"
to = "https://docs.google.com/spreadsheets/d/1gw_j5srMS2Zl0c1iFNYLjN--2IzI75UihsZlv5orPGs/edit?usp=sharing"
status = 301
force = true
